language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer require --no-update satooshi/php-coveralls '~1.0'
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
